<a href="https://colab.research.google.com/github/EnjamooriTejashwini/NASSCOM/blob/main/Week2/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

print("\n--- Task 1: Array Creation Shortcuts ---")


arr1_1 = np.arange(100)


arr1_2 = np.ones((3, 3), dtype=int)

arr1_3 = np.full((2, 4), 7)


arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])




print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])


val2_1 = data[2, 3]


row2_2 = data[0]


col2_3 = data[:, -1]


sub_arr2_4 = data[1:3, 0:2]


filtered_elements2_5 = data[data > 100]

print("2.1 Value:", val2_1)
print("2.2 First row:", row2_2)
print("2.3 Last column:", col2_3)
print("2.4 Sub-array:\n", sub_arr2_4)
print("2.5 Values greater than 100:", filtered_elements2_5)



print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))


arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)


even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("Original array:\n", arr3_1)
print("After replacing values less than 10:\n", arr3_2)
print("Number of even elements:", even_count3_3)



print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([
    [10, 5, 12],
    [3, 8, 15],
    [20, 7, 4]
])

sum4_1 = np.sum(arr4_1)


mean_cols4_2 = np.mean(arr4_1, axis=0)


max_rows4_3 = np.max(arr4_1, axis=1)


std4_4 = np.std(arr4_1)

print("Sum:", sum4_1)
print("Column means:", mean_cols4_2)
print("Row maximum values:", max_rows4_3)
print("Standard deviation:", std4_4)



print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

reshaped_arr5_2 = arr5_1.reshape(4, 6)

reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

flattened_arr5_4 = reshaped_arr5_2.ravel()

flattened_copy5_4 = reshaped_arr5_2.flatten()

print("4x6 array:\n", reshaped_arr5_2)
print("2x3x4 array:\n", reshaped_arr5_3)
print("Using ravel():", flattened_arr5_4)
print("Using flatten():", flattened_copy5_4)




print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

scalar = 10
vector = np.array([100, 200, 300])


result6_1 = arr6_1 + scalar


result6_2 = arr6_1 + vector

print("After adding scalar:\n", result6_1)
print("After adding vector:\n", result6_2)



print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])


view_arr7 = original_arr7[:]


view_arr7[0] = 99

print("Original after modifying view:", original_arr7)
print("View:", view_arr7)


copy_arr7 = original_arr7.copy()


copy_arr7[-1] = 0

print("Original after modifying copy:", original_arr7)
print("Copy:", copy_arr7)



print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([
    [1, 2],
    [3, 4]
])

arr8_b = np.array([
    [5, 6],
    [7, 8]
])

arr8_c = np.array([
    [9, 10]
])


vstack_arr8_1 = np.vstack((arr8_a, arr8_b))


hstack_arr8_2 = np.hstack((arr8_a, arr8_b))


combined_arr8_3 = np.vstack(
    (vstack_arr8_1, arr8_c)
)


part1, part2, part3 = np.array_split(
    combined_arr8_3,
    3
)

print("Vertical stack:\n", vstack_arr8_1)
print("Horizontal stack:\n", hstack_arr8_2)
print("Combined array:\n", combined_arr8_3)
print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)



print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([
    5, 2, 8, 1, 9, 4, 7, 3, 6
])

arr9_2d = np.array([
    [30, 20, 10],
    [60, 50, 40],
    [90, 80, 70]
])


sorted_arr9_1 = np.sort(arr9_1)


sorted_cols9_2 = np.sort(
    arr9_2d,
    axis=0
)


idx9_3 = np.where(arr9_1 == 9)


max_idx9_4 = np.argmax(arr9_1)

print("Sorted 1D array:", sorted_arr9_1)
print("Columns sorted:\n", sorted_cols9_2)
print("Index where value is 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)



--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[20 16 34 26 23]
 [18 48 38 23 10]]

--- Task 2: Indexing and Slicing with Arrays ---
2.1 Value: 120
2.2 First row: [10 20 30 40]
2.3 Last column: [ 40  80 120 160]
2.4 Sub-array:
 [[ 50  60]
 [ 90 100]]
2.5 Values greater than 100: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
Original array:
 [[12  3  7  5 13]
 [ 9 10 11 10 14]
 [16 19  7  4  3]
 [ 5  8 13  2 13]]
After replacing values less than 10:
 [[12  0  0  0 13]
 [ 0 10 11 10 14]
 [16 19  0  0  0]
 [ 0  0 13  0 13]]
Number of even elements: 8

--- Task 4: Aggregation Functions ---
Sum: 84
Column means: [11.          6.66666667 10.33333333]
Row maximum values: [12 15 20]
Standard deviation: 5.2493385