<a href="https://colab.research.google.com/github/EnjamooriTejashwini/NASSCOM/blob/main/Week2/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")


print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")


s1_1 = pd.Series([10, 20, 30, 40, 50])

print("\nPandas Series:")
print(s1_1)

np_array1_2 = np.random.randint(1, 101, size=(3, 4))

print("\nNumPy Array:")
print(np_array1_2)

df1_3 = pd.DataFrame(
    np_array1_2,
    columns=["A", "B", "C", "D"]
)

print("\nDataFrame:")
print(df1_3)



print("\n--- Task 2: Synthetic Data Generation for Practice ---")


df_sales = pd.DataFrame({
    "Date": pd.date_range(
        start="2023-01-01",
        end="2023-04-10",
        periods=100
    ),

    "Region": np.random.choice(
        ["East", "West", "North", "South"],
        size=100
    ),

    "Product": np.random.choice(
        ["Laptop", "Mouse", "Keyboard", "Monitor"],
        size=100
    ),

    "Sales": np.random.randint(
        100,
        1001,
        size=100
    ).astype(float),

    "Quantity": np.random.randint(
        1,
        11,
        size=100
    ).astype(float)
})


sales_nan_index = np.random.choice(
    df_sales.index,
    size=5,
    replace=False
)

df_sales.loc[sales_nan_index, "Sales"] = np.nan

quantity_nan_index = np.random.choice(
    df_sales.index,
    size=3,
    replace=False
)

df_sales.loc[quantity_nan_index, "Quantity"] = np.nan

print("\nFirst 5 rows of df_sales:")
print(df_sales.head())



print("\n--- Task 3: Indexing and Slicing in DataFrames ---")


df3_1 = df_sales[["Region", "Sales"]]

print("\n3.1 Region and Sales:")
print(df3_1.head())

df3_2 = df_sales[
    df_sales["Product"] == "Laptop"
]

print("\n3.2 Rows where Product is Laptop:")
print(df3_2.head())


df3_3 = df_sales[
    (df_sales["Region"] == "East") &
    (df_sales["Sales"] > 500)
]

print("\n3.3 East region with Sales greater than 500:")
print(df3_3)


val3_4 = df_sales.loc[
    df_sales["Product"] == "Monitor",
    "Sales"
].iloc[0]

print("\n3.4 First Monitor Sales value:")
print(val3_4)



print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")


missing_counts4_1 = df_sales.isnull().sum()

print("\n4.1 Missing values in each column:")
print(missing_counts4_1)

df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled["Sales"].mean()

df4_2_filled["Sales"] = (
    df4_2_filled["Sales"].fillna(sales_mean)
)

print("\n4.2 Missing values after filling Sales:")
print(df4_2_filled.isnull().sum())


df4_3_dropped = df_sales.dropna()

print("\n4.3 Data after dropping missing rows:")
print(df4_3_dropped.head())

print("\nNumber of rows after dropping:")
print(len(df4_3_dropped))



print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")



df_sales["Total_Revenue"] = (
    df_sales["Sales"] *
    df_sales["Quantity"]
)

print("\n5.1 Data with Total_Revenue:")
print(
    df_sales[
        ["Sales", "Quantity", "Total_Revenue"]
    ].head()
)


df5_2_sorted = df_sales.sort_values(
    by=["Date", "Sales"],
    ascending=[True, False]
)

print("\n5.2 Sorted Data:")
print(df5_2_sorted.head())


df5_3_grouped_region = (
    df_sales
    .groupby("Region")[["Sales", "Quantity"]]
    .sum()
)

print("\n5.3 Total Sales and Quantity by Region:")
print(df5_3_grouped_region)


df5_4_grouped_product = (
    df_sales
    .groupby("Product")["Sales"]
    .mean()
)

print("\n5.4 Average Sales by Product:")
print(df5_4_grouped_product)



--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

Pandas Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[33 12 76 79]
 [ 9 30 96 64]
 [92 27 13  3]]

DataFrame:
    A   B   C   D
0  33  12  76  79
1   9  30  96  64
2  92  27  13   3

--- Task 2: Synthetic Data Generation for Practice ---

First 5 rows of df_sales:
        Date Region   Product  Sales  Quantity
0 2023-01-01   West   Monitor  688.0       6.0
1 2023-01-02  North  Keyboard    NaN      10.0
2 2023-01-03  South    Laptop  125.0       5.0
3 2023-01-04   West   Monitor  579.0       8.0
4 2023-01-05   West    Laptop  494.0      10.0

--- Task 3: Indexing and Slicing in DataFrames ---

3.1 Region and Sales:
  Region  Sales
0   West  688.0
1  North    NaN
2  South  125.0
3   West  579.0
4   West  494.0

3.2 Rows where Product is Laptop:
        D